CREATE TABLE Address(
PostalCode CHAR(20),
StreetName CHAR(20),
House# INT,
City CHAR(20),
PRIMARY KEY(PostalCode, StreetName, House#));

CREATE TABLE User(
Name CHAR(20) PRIMARY KEY,
Password CHAR(20) NOT NULL,
PostalCode CHAR(20) NOT NULL,
StreetName CHAR(20) NOT NULL,
House# INT NOT NULL,
Certificate CHAR(20),
Budget INT,
FOREIGN KEY(PostalCode) REFERENCES Address(PostalCode) ON DELETE CASCADE,
FOREIGN KEY(StreetName) REFERENCES Address(StreetName) ON DELETE CASCADE,
FOREIGN KEY(House#) REFERENCES Address(House#) ON DELETE CASCADE));

CREATE TABLE Grocery(
GName CHAR(20) PRIMARY KEY,
Amount INT DEFAULT 0,
BuyingDate DATE,
Duration INT,
FOREIGN KEY BuyingDate REFERENCES GroceryDate(BuyingDate) ON DELETE CASCADE,
FOREIGN KEY Duration REFERENCES GroceryDate(Duration) ON DELETE CASCADE);

CREATE TABLE GroceryDate(
BuyingDate DATE,
Duration INT,
ExpiryDate DATE,
PRIMARY KEY(BuyingDate, Duration));

CREATE TABLE Buys(
UserId INT,
GName CHAR(20),
BuyingDate DATE,
PRIMARY(UserId, GName, BuyingDate),
FOREIGN KEY(UserId) REFERENCES User(UserId) ON DELETE CASCADE,
FOREIGN KEY(GName) REFERENCES Grocery(GName) ON DELETE CASCADE,
FOREIGN KEY(BuyingDate) REFERENCES Grocery(BuyingDate) ON DELETE CASCADE);

CREATE TABLE Recipe(
RecipeId INT PRIMARY KEY,
Name CHAR(20),
Tea CHAR(20) NOT NULL,
Calories INT DEFAULT 0,
Perl INT DEFAULT 0,
Jelly INT DEFAULT 0,
Lemon INT DEFAULT 0,
Orange INT DEFAULT 0);

CREATE TABLE Usage(
UseID INT PRIMARY KEY,
RecipeId INT,
Date DATE NOT NULL,
Tea CHAR(20) NOT NULL,
Calories INT DEFAULT 0,
Perl INT DEFAULT 0,
Jelly INT DEFAULT 0,
Lemon INT DEFAULT 0,
Orange INT DEFAULT 0,
FOREIGN KEY RecipeId REFERENCES Recipe(RecipeId) ON DELETE SET NULL);

CREATE TABLE Generates(
RecipeId INT,
UseID INT,
PRIMARY KEY(RecipeId, UseID),
FOREIGN KEY RecipeId REFERENCES Recipe ON DELETE CASCADE,
FOREIGN KEY UseId REFERENCES Usage ON DELETE CASCADE);

CREATE TABLE DailyReport (
ReportID INT,
UseID INT,
Date DATE NOT NULL,
UserID INT,
Perl INT DEFAULT 0,
Jelly INT DEFAULT 0,
Lemon INT DEFAULT 0,
Orange INT DEFAULT 0,
PRIMARY KEY(UseID, ReportID),
FOREIGN KEY (UserID) REFERENCES User ON DELETE CASCADE,
FOREIGN KEY (Date) REFERENCES ReportWeekDay ON DELETE CASCADE,
FOREIGN KEY (Weekday) REFERENCES ReportWeekDay ON DELETE CASCADE);

CREATE TABLE ReportWeekDay (
Date DATE PRIMARY KEY,
Weekday INT);

CREATE TABLE Supplier (
SupplierId INT PRIMARY KEY,
CompanyName CHAR(20) NOT NULL UNIQUE);

CREATE TABLE Supplies (
SupplierId INT,
GName CHAR(20),
PRIMARY KEY (SupplierId, GName),
FOREIGN KEY (SupplierId) REFERENCES Supplier ON DELETE CASCADE,
FOREIGN KEY (GName) REFERENCES Grocery ON DELETE CASCADE);

CREATE TABLE ShoppingList (
SListId INT PRIMARY KEY,
GName CHAR(20),
Amount INT NOT NULL,
Date DATE,
UserId INT,
FOREIGN KEY (UserId) REFERENCES User ON DELETE CASCADE,
FOREIGN KEY (GName) REFERENCES Grocery ON DELETE CASCADE);

CREATE TABLE Lists (
UseID INT,
GName CHAR(20),
SListId INT,
PRIMARY KEY (SListId, UseID, GName),
FOREIGN KEY (SListId) REFERENCES ShoppingList ON DELETE CASCADE,
FOREIGN KEY (GName) REFERENCES Grocery ON DELETE CASCADE,
FOREIGN KEY (UseId) REFERENCES Usage ON DELETE CASCADE);

-- CREATE TABLE User (
--     Id INT PRIMARY KEY,
--     Name CHAR(20) NOT NULL,
--     StreetName CHAR(20),
--     HouseNumber INT,
--     City CHAR(20),
--     PostalCode CHAR(20)
-- );

INSERT INTO branch VALUES (1, "ABC", "123 Charming Ave", "Vancouver", "6041234567");
INSERT INTO branch VALUES (2, "DEF", "123 Coco Ave", "Vancouver", "6044567890");